name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
        # ensure pytest is available
        python -m pip install pytest

    - name: Show installed packages (debug)
      run: |
        python -m pip show pytest || true
        python -m pip list | sed -n '1,200p'

    - name: Run tests
      run: python -m pytest -q
